global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
    basic_auth:
      username: "1641907"
      password: glc_eyJvIjoiMTE1Mzc5MyIsIm4iOiJzdGFjay05NjMxMTAtaW50ZWdyYXRpb24tbWJ0aTEiLCJrIjoiOGY0OUc2NzAxOU9Xc1JuakJRbTlxM1pDIiwibSI6eyJyIjoicHJvZC11cy13ZXN0LTAifX0=
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]